backend:
  name: github
  repo: perryjobs/heaven-prophetic
  branch: main
  site_domain: https://perryjobs.github.io/heaven-prophetic
  base_url: https://api.github.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "sermons"
    label: "Sermons"
    folder: "content/sermons"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "YouTube or Facebook Link", name: "video", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Event Name", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Details", name: "body", widget: "markdown" }
