backend:
  name: github
  repo: perryjobs/heaven-prophetic  # Your GitHub repository
  branch: main              # Branch to use

media_folder: "static/uploads"   # Folder to store uploaded media
public_folder: "/uploads"         # Public URL path

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
